Bac 140 monitor withdrawals
Tetrics-io/backend pull request #118
Opened 2024-12-24 19:47 UTC by Ritika-Agrawal811

2024-12-25 05:37 UTC, gopherine requested changes

2024-12-25 05:37 UTC, gopherine commented on internal/services/notification/slack/slack.go
>  	color := "#36a64f" // green for success
fix: should be const

2024-12-25 05:37 UTC, gopherine commented on internal/services/notification/slack/slack.go
>  		Ts:     json.Number(fmt.Sprintf("%d", time.Now().Unix())),
sort of confusing why this conversion is needed - ?? what type is Ts is it number type or string type ? cant we just pass either  int64 or string ?

2024-12-25 05:47 UTC, Ritika-Agrawal811 commented on internal/services/notification/slack/slack.go
>  		Ts:     json.Number(fmt.Sprintf("%d", time.Now().Unix())),
Ts (timestamp) is showing json.Number type so it won't work without that conversion

``Ts json.Number `json:"ts,omitempty"``

2024-12-26 04:26 UTC, gopherine approved these changes

2024-12-26 04:44 UTC, merged