Bac 177 store a users order details in db in order tracking service
Tetrics-io/backend pull request #120
Opened 2024-12-25 02:42 UTC by Ritika-Agrawal811

2024-12-25 06:00 UTC, gopherine requested changes

2024-12-25 06:00 UTC, gopherine commented on internal/api/websockets/handlers/fix_handler.go
>  	case "close_order":
switch cases should ideally have iota
https://bitfieldconsulting.com/posts/iota you can refer here its a good starting guide

2024-12-25 06:00 UTC, gopherine commented on internal/api/websockets/handlers/fix_handler.go
> +	 if _err := h.orderService.StoreOrderDetails(orderParams); _err != nil {
inconsistent naming why use _err here

while below you use err

standard:

1. user either descriptive errorname like orderDetailsErr
or just use err

also this syntax is scoped so you can safely use err here and below

2024-12-25 06:00 UTC, gopherine commented on internal/api/websockets/handlers/fix_handler.go
> +		return utils.WrapError(_err, "failed to store order details")
weired some places we have this wraperror utils some places we are using fmt.Errorf my understanding is direct usage of fmt.Errorf should be good why do we need to wrap is there a specific error structure you are trying to achieve ?

if yes can we make this consistant across the app!!

2024-12-25 06:00 UTC, gopherine commented on internal/api/websockets/handlers/fix_handler.go
> +		return fmt.Errorf("failed to place order: %w", err)
as said above i think this works over all i am not sure why we need utils.WrapErr?

2024-12-25 06:00 UTC, gopherine commented on internal/api/websockets/handlers/fix_handler.go
> +				log.Info().Msgf("error is ====> %v", _err)
weired error message
firstly 

error should be logged as

log.Error().Err(err).Msg("custom err message")

use of symbols like ====> is highly discouraged

2024-12-25 06:00 UTC, gopherine commented on internal/api/websockets/handlers/fix_handler.go
> +			 if _err := h.orderService.ClosePosition(status.Status, orderReq.Wallet, *orderReq.PositionId, orderReq.MarkPrice, orderReq.Price); _err != nil {
some places use pointer and some value
ideally these are the factors to consider

1. value is small
2. you dont need nil checks
3. data is immutable and no modification is required
pass by value

1. data is large like whole struct
2. you need nil checks
3. some modifications are needed

pass by reference ( pointer)

2024-12-25 06:00 UTC, gopherine commented on internal/domain/entities/order.go
> +// }
if not used why is it here?

2024-12-25 06:00 UTC, gopherine commented on pkg/fix/order_tracker.go
> +            return nil, errors.New("neither ClOrdID nor OrigClOrdID found")
should be defined in err constant at the top of the file

can be named

ErrClOrdID not found

also there is a typo

2024-12-26 06:07 UTC, Ritika-Agrawal811 commented on internal/api/websockets/handlers/fix_handler.go
> +	 if _err := h.orderService.StoreOrderDetails(orderParams); _err != nil {
Fixed the naming. Using err now everywhere

2024-12-26 06:08 UTC, Ritika-Agrawal811 commented on internal/api/websockets/handlers/fix_handler.go
> +		return utils.WrapError(_err, "failed to store order details")
I want to have a single function to handle all errors. Have modified utils.WrapError and now using that everywhere.

2024-12-26 06:09 UTC, Ritika-Agrawal811 commented on internal/api/websockets/handlers/fix_handler.go
> +		return fmt.Errorf("failed to place order: %w", err)
Created a common utils.WrapError to show errors. Using that in all places now

2024-12-26 06:09 UTC, Ritika-Agrawal811 commented on internal/api/websockets/handlers/fix_handler.go
> +				log.Info().Msgf("error is ====> %v", _err)
Removed the unnecessary log statements like these and added proper error message using log.Error().Err().Msg() method

2024-12-26 06:10 UTC, Ritika-Agrawal811 commented on internal/domain/entities/order.go
> +// }
Removed the uncommented code

2024-12-26 06:11 UTC, Ritika-Agrawal811 commented on pkg/fix/order_tracker.go
> +            return nil, errors.New("neither ClOrdID nor OrigClOrdID found")
Changed this code to use utils.WrapError method to handle errors.

For some messages, ClOrdID is available in orgClOrdId so added conditions to handle that and not skip any order status messages from FIX

2024-12-26 06:13 UTC, Ritika-Agrawal811 commented on internal/api/websockets/handlers/fix_handler.go
> +			 if _err := h.orderService.ClosePosition(status.Status, orderReq.Wallet, *orderReq.PositionId, orderReq.MarkPrice, orderReq.Price); _err != nil {
changed the position id param back to int instead of pointer. Also added validation checks for it.

2024-12-26 06:22 UTC, Ritika-Agrawal811 commented on internal/api/websockets/handlers/fix_handler.go
> +	 if err := h.orderService.StoreOrderDetails(orderParams); err != nil {
Fixed the naming for error everywhere. @gopherine 

https://github.com/Goemon-xyz/backend/pull/120#discussion_r1897125155

2024-12-26 06:28 UTC, Ritika-Agrawal811 commented on internal/api/websockets/handlers/fix_handler.go
> +			 if err := h.orderService.ClosePosition(status.Status, orderReq.Wallet, orderReq.PositionId, orderReq.MarkPrice, orderReq.Price); err != nil {
Removed the pointer for position ID and added checks to validate it. @gopherine 

https://github.com/Goemon-xyz/backend/pull/120#discussion_r1897127697

2024-12-26 06:29 UTC, Ritika-Agrawal811 commented on internal/domain/entities/order.go
> -// type UserPositionDetails struct {
removed the commented code. @gopherine 

https://github.com/Goemon-xyz/backend/pull/120#discussion_r1897127845

2024-12-26 07:04 UTC, gopherine approved these changes

2024-12-26 07:09 UTC, merged